stock/urls.py
from django.urls import path
from .views import StockListView

urlpatterns = [
    path('', StockListView.as_view(), name='home'),
]

tracker/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path("", include("stock.urls")),
]

stock/models.py
from django.db import models
from django.urls import reverse

# Create your models here.
class Stock(models.Model):
    ticker = models.CharField(max_length=10, unique=True)
    info = models.JSONField(default=dict, blank=True, null=True)
    history = models.JSONField(default=dict, blank=True, null=True)

    def __str__(self):
        return self.ticker
    
    def get_absolute_url(self):
        return reverse('stock_detail', args=[str(self.id)])

user/models.py
from django.db import models

# Create your models here.

stock/views.py
from .models import Stock
from django.views.generic import ListView
from django_q.tasks import schedule
from django_q.models import Schedule
from django.shortcuts import render

schedule('stock.tasks.update_stock_info', schedule_type=Schedule.MINUTES, minutes=5, repeats=-1)

class StockListView(ListView):
    model = Stock
    template_name = 'home.html'

user/views.py
from django.shortcuts import render

# Create your views here.

templates/base.html
{% load static %}
<html>
<head>
    <title>Easy Tracker</title>
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bulma@0.9.4/css/bulma.min.css"></head>
<body>
    <section class="section">
        <div class="container">
            <h1 class="title is-1">
                <a href="{% url 'home' %}">
                    Easy Tracker
                </a>
            </h1>
        </div>
    </section>
        <section class="section">
            {% block content %}
            {% endblock content %}
        </section>
</body>
</html>

templates/home.html
{% extends "base.html" %}

{% block content %}
<div class="columns">
{% for stock in stock_list %}
  <div class="column">
    <div class="box">
    <h3 class="title is-3"><a href="">{{ stock.ticker }}</a></h3>
    <p>Current Price: {{ stock.info.currentPrice }}</p>
    <p>Previous Close: {{ stock.info.previousClose }}</p>
    <p>Open: {{ stock.info.open }}</p>
    <p>Today High: {{ stock.info.dayHigh }}</p>
    <p>Today Low: {{ stock.info.dayLow }}</p>
    <p>Today change: {{ stock.info.change }} / {{ stock.info.changePercent }}%</p>
    <p>Last day change: {{ stock.info.lastDayChange }} / {{stock.info.lastDayChangePercent}}%</p>
    </div>
  </div>
{% endfor %}
</div>
{% endblock content %}